# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'province',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='CityDistrict',
            new_name='CityRegency',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='city_district',
            new_name='city_regency',
        ),
        migrations.AlterModelTable(
            name='cityregency',
            table='city_regency',
        ),
    ]
