# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_cityregency_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityregency',
            name='province',
        ),
    ]
