# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_remove_cityregency_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityregency',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cityregencys', to='orm.Province'),
        ),
    ]
