# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20171228_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGrafik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('usia', models.CharField(blank=True, max_length=50, null=True)),
                ('k_busur', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
