# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_testgrafik'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=orm.FileUploader.file_club)),
                ('filename', models.CharField(default=None, max_length=30)),
                ('file_ext', models.CharField(default=None, max_length=30)),
                ('mimetype', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'club_files',
            },
        ),
        migrations.AddField(
            model_name='anggota',
            name='picture',
            field=models.ImageField(blank=True, default='user/avatar.png', help_text='Upload Potomu sebagai gambar profile', null=True, upload_to=orm.FileUploader.file_profile),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload Logo klub', null=True, upload_to='club/logo'),
        ),
        migrations.AddField(
            model_name='clubfiles',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubfiles', to='orm.Club'),
        ),
    ]
