# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20180123_0628'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anggota',
            table=None,
        ),
    ]
