# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_auto_20180124_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='anggota',
            table='anggota',
        ),
    ]
