# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0012_auto_20180317_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityregency',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
