# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0013_cityregency_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityregency',
            name='user',
        ),
    ]
