# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0015_cityregency_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabangFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=orm.FileUploader.file_club)),
                ('filename', models.CharField(default=None, max_length=30)),
                ('file_ext', models.CharField(default=None, max_length=30)),
                ('mimetype', models.CharField(default=None, max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabangfiles', to='orm.Club')),
            ],
            options={
                'db_table': 'cabang_files',
            },
        ),
        migrations.AddField(
            model_name='cityregency',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityregency',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload Logo klub', null=True, upload_to='cabang/logo'),
        ),
        migrations.AddField(
            model_name='cityregency',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
